spring.application.name=meditation

# User-facing service brand
app.brand.name=MSDS
app.brand.tagline=Meditate. Slow Down. Stay.

spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/msds_db
spring.datasource.username=msds
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.hibernate.ddl-auto=update